name: flutter_games
description: "a flutter project to showcase different types of games"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  connectivity_plus: ^6.1.0
  dio_smart_retry: ^6.0.0
  dio: ^5.7.0
  get_it: ^8.0.2
  logging: ^1.3.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  get_storage: ^2.1.1
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  bloc_concurrency: ^0.2.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  flutter_emoji: ^2.5.1
  flip_card: ^0.7.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
