[book]
authors = ["cheatsnake"]
language = "en"
multilingual = false
src = "docs"
title = "Shadify"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/cheatsnake/shadify"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/cheatsnake/shadify/edit/master/{path}"

[output.html.print]
enable = false
